cmake_minimum_required(VERSION 3.16)
project(HeatEquationWithDelaunayTriangulation)

set(CMAKE_CXX_STANDARD 17)

add_executable(HeatEquationWithDelaunayTriangulation main.cpp Triangulation/Point_2.h Triangulation/vector_stuff.h Triangulation/DCEL.cpp Triangulation/DCEL.h Triangulation/DelaunayTree.cpp Triangulation/DelaunayTree.h Triangulation/DelaunayTriangulation.cpp Triangulation/DelaunayTriangulation.h Triangulation/magic_constants.h FiniteElementMethod/FiniteElementMethodHeatEquation.cpp FiniteElementMethod/FiniteElementMethodHeatEquation.h Triangulation/DTO.h)